//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZXStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZXStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _112_Tick_Green_32x32_72 {
            get {
                object obj = ResourceManager.GetObject("_112_Tick_Green_32x32_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2000px_Simple_Monitor_Icon_svg {
            get {
                object obj = ResourceManager.GetObject("_2000px_Simple_Monitor_Icon_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _2000px_Simple_Monitor_Icon_svg_png {
            get {
                object obj = ResourceManager.GetObject("_2000px_Simple_Monitor_Icon_svg_png", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _48 {
            get {
                object obj = ResourceManager.GetObject("_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _499_512 {
            get {
                object obj = ResourceManager.GetObject("_499_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap asm {
            get {
                object obj = ResourceManager.GetObject("asm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bookmark_Red_16xLG {
            get {
                object obj = ResourceManager.GetObject("bookmark_Red_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Browser {
            get {
                object obj = ResourceManager.GetObject("Browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CharacterSet {
            get {
                return ResourceManager.GetString("CharacterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloseSolution_48x {
            get {
                object obj = ResourceManager.GetObject("CloseSolution_48x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compile_build_rebuild_make_512 {
            get {
                object obj = ResourceManager.GetObject("compile_build_rebuild_make_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compiler {
            get {
                object obj = ResourceManager.GetObject("compiler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cross {
            get {
                object obj = ResourceManager.GetObject("Cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DebugFaster {
            get {
                object obj = ResourceManager.GetObject("DebugFaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DebugSlower {
            get {
                object obj = ResourceManager.GetObject("DebugSlower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap decreased_proportionally_square_button_512 {
            get {
                object obj = ResourceManager.GetObject("decreased_proportionally_square_button_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disassembler {
            get {
                object obj = ResourceManager.GetObject("disassembler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_AutoHide {
            get {
                object obj = ResourceManager.GetObject("DockPane_AutoHide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_Close {
            get {
                object obj = ResourceManager.GetObject("DockPane_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_Dock {
            get {
                object obj = ResourceManager.GetObject("DockPane_Dock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneStrip_ScrollLeftDisabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_ScrollLeftDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneStrip_ScrollLeftEnabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_ScrollLeftEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Faster {
            get {
                object obj = ResourceManager.GetObject("Faster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear_32xLG {
            get {
                object obj = ResourceManager.GetObject("gear_32xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenFlag {
            get {
                object obj = ResourceManager.GetObject("GreenFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HideListing {
            get {
                object obj = ResourceManager.GetObject("HideListing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDE01 {
            get {
                object obj = ResourceManager.GetObject("IDE01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap increased_proportionally_square_button_512 {
            get {
                object obj = ResourceManager.GetObject("increased_proportionally_square_button_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftArrow {
            get {
                object obj = ResourceManager.GetObject("LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linenumberes {
            get {
                object obj = ResourceManager.GetObject("linenumberes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_512 {
            get {
                object obj = ResourceManager.GetObject("map_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_go_512 {
            get {
                object obj = ResourceManager.GetObject("map_go_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mouse_click_512_green {
            get {
                object obj = ResourceManager.GetObject("mouse_click_512_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mouse_click_512_red {
            get {
                object obj = ResourceManager.GetObject("mouse_click_512_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewFile {
            get {
                object obj = ResourceManager.GetObject("NewFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewProject {
            get {
                object obj = ResourceManager.GetObject("NewProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Normal {
            get {
                object obj = ResourceManager.GetObject("Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_folder_with_document_318_48982 {
            get {
                object obj = ResourceManager.GetObject("open_folder_with_document_318_48982", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFolder_32x {
            get {
                object obj = ResourceManager.GetObject("OpenFolder_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenProject {
            get {
                object obj = ResourceManager.GetObject("OpenProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Output {
            get {
                object obj = ResourceManager.GetObject("Output", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseHS {
            get {
                object obj = ResourceManager.GetObject("PauseHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayHS {
            get {
                object obj = ResourceManager.GetObject("PlayHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayStep_ActionGrey_32x {
            get {
                object obj = ResourceManager.GetObject("PlayStep_ActionGrey_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Poke {
            get {
                object obj = ResourceManager.GetObject("Poke", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Project {
            get {
                object obj = ResourceManager.GetObject("Project", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PropertyBackground {
            get {
                object obj = ResourceManager.GetObject("PropertyBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PropertyHighlight {
            get {
                object obj = ResourceManager.GetObject("PropertyHighlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedFlag {
            get {
                object obj = ResourceManager.GetObject("RedFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Restart1green {
            get {
                object obj = ResourceManager.GetObject("Restart1green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Restart1red {
            get {
                object obj = ResourceManager.GetObject("Restart1red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_32x {
            get {
                object obj = ResourceManager.GetObject("Save_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveAll_32x {
            get {
                object obj = ResourceManager.GetObject("SaveAll_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveAs_16x {
            get {
                object obj = ResourceManager.GetObject("SaveAs_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Separator {
            get {
                object obj = ResourceManager.GetObject("Separator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowListing {
            get {
                object obj = ResourceManager.GetObject("ShowListing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spreadsheet {
            get {
                object obj = ResourceManager.GetObject("spreadsheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spreadsheetclose {
            get {
                object obj = ResourceManager.GetObject("spreadsheetclose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Step_32xLG {
            get {
                object obj = ResourceManager.GetObject("Step_32xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stepout {
            get {
                object obj = ResourceManager.GetObject("stepout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stepovr {
            get {
                object obj = ResourceManager.GetObject("stepovr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tick {
            get {
                object obj = ResourceManager.GetObject("Tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up_folder_icon_54527 {
            get {
                object obj = ResourceManager.GetObject("up_folder_icon_54527", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UpArrow {
            get {
                object obj = ResourceManager.GetObject("UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UpArrowHilight {
            get {
                object obj = ResourceManager.GetObject("UpArrowHilight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000	THE &apos;START&apos;	0
        ///0008	THE &apos;ERROR&apos; RESTART	8
        ///0010	THE &apos;PRINT A CHARACTER&apos; RESTART	16
        ///0018	THE &apos;COLLECT CHARACTER&apos; RESTART	24
        ///0020	THE &apos;COLLECT NEXT CHARACTER&apos; RESTART	32
        ///0028	THE &apos;CALCULATOR&apos; RESTART	40
        ///0030	THE &apos;MAKE BC SPACES&apos; RESTART	48
        ///0038	THE &apos;MASKABLE INTERRUPT&apos; ROUTINE	56
        ///0053	THE &apos;ERROR-2&apos; ROUTINE	83
        ///0074	THE &apos;CH-ADD+1&apos; SUBROUTINE	116
        ///007D	THE &apos;SKIP-OVER&apos; SUBROUTINE	125
        ///028E	THE &apos;KEYBOARD SCANNING&apos; SUBROUTINE	654
        ///02BF	THE &apos;KEYBOARD&apos; SUBROUTINE	703
        ///031E	THE &apos;K-TEST&apos; SUBROUTINE	798
        ///033 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XRefAddress {
            get {
                return ResourceManager.GetString("XRefAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000	THE &apos;START&apos;	0
        ///0008	THE &apos;ERROR&apos; RESTART	8
        ///0010	THE &apos;PRINT A CHARACTER&apos; RESTART	16
        ///0013	Unused	19
        ///0018	THE &apos;COLLECT CHARACTER&apos; RESTART	24
        ///0020	THE &apos;COLLECT NEXT CHARACTER&apos; RESTART	32
        ///0025	Unused	37
        ///0028	THE &apos;CALCULATOR&apos; RESTART	40
        ///002B	Unused	43
        ///0030	THE &apos;MAKE BC SPACES&apos; RESTART	48
        ///0038	THE &apos;MASKABLE INTERRUPT&apos; ROUTINE	56
        ///0053	THE &apos;ERROR-2&apos; ROUTINE	83
        ///005F	Unused	95
        ///0066	THE &apos;NON-MASKABLE INTERRUPT&apos; ROUTINE	102
        ///0074	THE &apos;CH-ADD+1&apos; SUBROUTINE	116
        ///007D	THE &apos;SKIP-OVER&apos; SUBROUTINE	125
        ///0095	TH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XRefAll {
            get {
                return ResourceManager.GetString("XRefAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0205	THE KEY TABLES	517
        ///046E	THE &apos;SEMI-TONE&apos; TABLE	1134
        ///0A11	THE &apos;CONTROL CHARACTER&apos; TABLE	2577
        ///0FA0	THE &apos;EDITING KEYS&apos; TABLE	4000
        ///15AF	THE &apos;INITIAL CHANNEL INFORMATION&apos;	5551
        ///15C6	THE &apos;INITIAL STREAM DATA&apos;	5574
        ///162D	THE &apos;CHANNEL CODE LOOK-UP&apos; TABLE	5677
        ///1716	THE &apos;CLOSE STREAM LOOK-UP&apos; TABLE	5910
        ///177A	THE &apos;OPEN STREAM LOOK-UP&apos; TABLE	6010
        ///1A48	THE SYNTAX TABLES	6728
        ///1C01	THE &apos;COMMAND CLASS&apos; TABLE	7169
        ///2596	THE SCANNING FUNCTION TABLE	9622
        ///2795	THE TABLE OF OPERATORS	10133
        ///27B0	THE TABLE OF PRIORI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XRefData {
            get {
                return ResourceManager.GetString("XRefData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00	jump-true	0
        ///01	exchange	1
        ///02	delete	2
        ///03	subtract	3
        ///04	multiply	4
        ///05	division	5
        ///06	to-power	6
        ///07	or	7
        ///08	no-&amp;-no	8
        ///09	no-l-eql	9
        ///0A	no-gr-eq	10
        ///0B	nos-neql	11
        ///0C	no-grtr	12
        ///0D	no-less	13
        ///0E	nos-eql	14
        ///0F	addition	15
        ///10	str-&amp;-no	16
        ///11	str-l-eql	17
        ///12	str-gr-eq	18
        ///13	strs-neql	19
        ///14	str-grtr	20
        ///15	str-less	21
        ///16	strs-eql	22
        ///17	strs-add	23
        ///18	val$	24
        ///19	usr-$	25
        ///1A	read-in	26
        ///1B	negate	27
        ///1C	code	28
        ///1D	val	29
        ///1E	len	30
        ///1F	sin	31
        ///20	cos	32
        ///21	tan	33
        ///22	asn	34
        ///23	acs	35
        ///24	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XRefFPRoutines {
            get {
                return ResourceManager.GetString("XRefFPRoutines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000	START	0
        ///0008	ERROR-1	8
        ///0010	PRINT-A-1	16
        ///0018	GET-CHAR	24
        ///001C	TEST-CHAR	28
        ///0020	NEXT-CHAR	32
        ///0028	FP-CALC	40
        ///0030	BC-SPACES	48
        ///0038	MASK-INT	56
        ///0048	KEY-INT	72
        ///0053	ERROR-2	83
        ///0055	ERROR-3	85
        ///0066	RESET	102
        ///0070	NO-RESET	112
        ///0074	CH-ADD+1	116
        ///0077	TEMP-PTR1	119
        ///0078	TEMP-PTR2	120
        ///007D	SKIP-OVER	125
        ///0090	SKIPS	144
        ///028E	KEY-SCAN	654
        ///0296	KEY-LINE	662
        ///029F	KEY-3KEYS	671
        ///02A1	KEY-BITS	673
        ///02AB	KEY-DONE	683
        ///02BF	KEYBOARD	703
        ///02C6	K-ST-LOOP	710
        ///02D1	K-CH-SET	721
        ///02F1	K-NEW	753
        ///03 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XRefLabels {
            get {
                return ResourceManager.GetString("XRefLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0095	THE TOKEN TABLE	149
        ///09A1	THE CASSETTE MESSAGES	2465
        ///1391	THE REPORT MESSAGES	5009
        ///1539	THE COPYRIGHT MESSAGE	5433.
        /// </summary>
        internal static string XRefMessages {
            get {
                return ResourceManager.GetString("XRefMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5C00	23552	Used in reading the keyboard	N8	KSTATE	Used in reading the keyboard.
        ///5C08	23560	Last key pressed	Nl	LAST K	Stores newly pressed key.
        ///5C09	23561	Time that a key must be held down before it repeats	1	REPDEL	Time (in 50ths of a second in 60ths of a second in N. America) that a key must be held down before it repeats. This starts off at 35, but you can POKE in other values.
        ///5C0A	23562	Delay between successive repeats of a key held down	1	REPPER	Delay (in 50ths of a second in 60ths of a second in N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XRefSystemVariables {
            get {
                return ResourceManager.GetString("XRefSystemVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Zilog {
            get {
                object obj = ResourceManager.GetObject("Zilog", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Zilog_png {
            get {
                object obj = ResourceManager.GetObject("Zilog_png", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zilog1 {
            get {
                object obj = ResourceManager.GetObject("Zilog1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon zilog1_png {
            get {
                object obj = ResourceManager.GetObject("zilog1_png", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zilog11 {
            get {
                object obj = ResourceManager.GetObject("zilog11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ZXMachine48k_png {
            get {
                object obj = ResourceManager.GetObject("ZXMachine48k_png", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
