using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZXStudio
{
    internal static partial class Opcodes
    {
        public static DOpcode[] DDCBPrefix = new DOpcode[]
        {
            new DOpcode (0x00,"LD B,RLC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x01,"LD C,RLC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x02,"LD D,RLC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x03,"LD E,RLC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x04,"LD H,RLC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x05,"LD L,RLC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x06,"RLC (IX$x)",23,0,"Indexed",false),
            new DOpcode (0x07,"LD A,RLC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x08,"LD B,RRC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x09,"LD C,RRC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x0A,"LD D,RRC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x0B,"LD E,RRC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x0C,"LD H,RRC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x0D,"LD L,RRC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x0E,"RRC (IX$x)",23,0,"Indexed",false),
            new DOpcode (0x0F,"LD A,RRC (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x10,"LD B,RL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x11,"LD C,RL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x12,"LD D,RL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x13,"LD E,RL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x14,"LD H,RL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x15,"LD L,RL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x16,"RL (IX$x)",23,0,"Indexed",false),
            new DOpcode (0x17,"LD A,RL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x18,"LD B,RR (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x19,"LD C,RR (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x1A,"LD D,RR (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x1B,"LD E,RR (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x1C,"LD H,RR (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x1D,"LD L,RR (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x1E,"RR (IX$x)",23,0,"Indexed",false),
            new DOpcode (0x1F,"LD A,RR (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x20,"LD B,SLA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x21,"LD C,SLA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x22,"LD D,SLA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x23,"LD E,SLA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x24,"LD H,SLA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x25,"LD L,SLA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x26,"SLA (IX$x)",23,0,"Indexed",false),
            new DOpcode (0x27,"LD A,SLA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x28,"LD B,SRA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x29,"LD C,SRA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x2A,"LD D,SRA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x2B,"LD E,SRA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x2C,"LD H,SRA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x2D,"LD L,SRA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x2E,"SRA (IX$x)",23,0,"Indexed",false),
            new DOpcode (0x2F,"LD A,SRA (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x30,"LD B,SLL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x31,"LD C,SLL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x32,"LD D,SLL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x33,"LD E,SLL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x34,"LD H,SLL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x35,"LD L,SLL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x36,"SLL (IX$x)",23,0,"Indexed",false),
            new DOpcode (0x37,"LD A,SLL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x38,"LD B,SRL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x39,"LD C,SRL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x3A,"LD D,SRL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x3B,"LD E,SRL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x3C,"LD H,SRL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x3D,"LD L,SRL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x3E,"SRL (IX$x)",23,0,"Indexed",false),
            new DOpcode (0x3F,"LD A,SRL (IX$x)",23,0,"Indexed",true),
            new DOpcode (0x40,"BIT 0,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x41,"BIT 0,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x42,"BIT 0,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x43,"BIT 0,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x44,"BIT 0,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x45,"BIT 0,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x46,"BIT 0,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x47,"BIT 0,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x48,"BIT 1,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x49,"BIT 1,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x4A,"BIT 1,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x4B,"BIT 1,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x4C,"BIT 1,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x4D,"BIT 1,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x4E,"BIT 1,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x4F,"BIT 1,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x50,"BIT 2,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x51,"BIT 2,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x52,"BIT 2,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x53,"BIT 2,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x54,"BIT 2,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x55,"BIT 2,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x56,"BIT 2,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x57,"BIT 2,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x58,"BIT 3,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x59,"BIT 3,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x5A,"BIT 3,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x5B,"BIT 3,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x5C,"BIT 3,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x5D,"BIT 3,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x5E,"BIT 3,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x5F,"BIT 3,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x60,"BIT 4,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x61,"BIT 4,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x62,"BIT 4,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x63,"BIT 4,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x64,"BIT 4,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x65,"BIT 4,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x66,"BIT 4,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x67,"BIT 4,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x68,"BIT 5,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x69,"BIT 5,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x6A,"BIT 5,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x6B,"BIT 5,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x6C,"BIT 5,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x6D,"BIT 5,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x6E,"BIT 5,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x6F,"BIT 5,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x70,"BIT 6,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x71,"BIT 6,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x72,"BIT 6,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x73,"BIT 6,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x74,"BIT 6,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x75,"BIT 6,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x76,"BIT 6,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x77,"BIT 6,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x78,"BIT 7,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x79,"BIT 7,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x7A,"BIT 7,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x7B,"BIT 7,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x7C,"BIT 7,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x7D,"BIT 7,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x7E,"BIT 7,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x7F,"BIT 7,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x80,"LD B,RES 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x81,"LD C,RES 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x82,"LD D,RES 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x83,"LD E,RES 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x84,"LD H,RES 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x85,"LD L,RES 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x86,"RES 0,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x87,"LD A,RES 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x88,"LD B,RES 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x89,"LD C,RES 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x8A,"LD D,RES 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x8B,"LD E,RES 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x8C,"LD H,RES 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x8D,"LD L,RES 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x8E,"RES 1,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x8F,"LD A,RES 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x90,"LD B,RES 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x91,"LD C,RES 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x92,"LD D,RES 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x93,"LD E,RES 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x94,"LD H,RES 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x95,"LD L,RES 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x96,"RES 2,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x97,"LD A,RES 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x98,"LD B,RES 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x99,"LD C,RES 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x9A,"LD D,RES 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x9B,"LD E,RES 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x9C,"LD H,RES 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x9D,"LD L,RES 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0x9E,"RES 3,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0x9F,"LD A,RES 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xA0,"LD B,RES 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xA1,"LD C,RES 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xA2,"LD D,RES 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xA3,"LD E,RES 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xA4,"LD H,RES 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xA5,"LD L,RES 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xA6,"RES 4,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xA7,"LD A,RES 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xA8,"LD B,RES 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xA9,"LD C,RES 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xAA,"LD D,RES 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xAB,"LD E,RES 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xAC,"LD H,RES 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xAD,"LD L,RES 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xAE,"RES 5,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xAF,"LD A,RES 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xB0,"LD B,RES 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xB1,"LD C,RES 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xB2,"LD D,RES 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xB3,"LD E,RES 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xB4,"LD H,RES 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xB5,"LD L,RES 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xB6,"RES 6,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xB7,"LD A,RES 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xB8,"LD B,RES 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xB9,"LD C,RES 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xBA,"LD D,RES 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xBB,"LD E,RES 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xBC,"LD H,RES 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xBD,"LD L,RES 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xBE,"RES 7,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xBF,"LD A,RES 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xC0,"LD B,SET 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xC1,"LD C,SET 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xC2,"LD D,SET 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xC3,"LD E,SET 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xC4,"LD H,SET 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xC5,"LD L,SET 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xC6,"SET 0,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xC7,"LD A,SET 0,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xC8,"LD B,SET 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xC9,"LD C,SET 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xCA,"LD D,SET 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xCB,"LD E,SET 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xCC,"LD H,SET 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xCD,"LD L,SET 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xCE,"SET 1,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xCF,"LD A,SET 1,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xD0,"LD B,SET 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xD1,"LD C,SET 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xD2,"LD D,SET 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xD3,"LD E,SET 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xD4,"LD H,SET 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xD5,"LD L,SET 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xD6,"SET 2,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xD7,"LD A,SET 2,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xD8,"LD B,SET 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xD9,"LD C,SET 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xDA,"LD D,SET 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xDB,"LD E,SET 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xDC,"LD H,SET 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xDD,"LD L,SET 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xDE,"SET 3,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xDF,"LD A,SET 3,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xE0,"LD B,SET 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xE1,"LD C,SET 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xE2,"LD D,SET 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xE3,"LD E,SET 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xE4,"LD H,SET 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xE5,"LD L,SET 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xE6,"SET 4,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xE7,"LD A,SET 4,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xE8,"LD B,SET 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xE9,"LD C,SET 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xEA,"LD D,SET 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xEB,"LD E,SET 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xEC,"LD H,SET 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xED,"LD L,SET 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xEE,"SET 5,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xEF,"LD A,SET 5,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xF0,"LD B,SET 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xF1,"LD C,SET 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xF2,"LD D,SET 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xF3,"LD E,SET 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xF4,"LD H,SET 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xF5,"LD L,SET 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xF6,"SET 6,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xF7,"LD A,SET 6,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xF8,"LD B,SET 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xF9,"LD C,SET 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xFA,"LD D,SET 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xFB,"LD E,SET 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xFC,"LD H,SET 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xFD,"LD L,SET 7,(IX$x)",23,0,"Indexed",true),
            new DOpcode (0xFE,"SET 7,(IX$x)",23,0,"Indexed",false),
            new DOpcode (0xFF,"LD A,SET 7,(IX$x)",23,0,"Indexed",true)
        };
    }
}

