using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZXStudio
{
    internal static partial class Opcodes
    {
        internal static void Touch()
        { }

        public static DOpcode[] NoPrefix = new DOpcode[]
        {
            new DOpcode (0x00,"NOP",4,0,"",true),
            new DOpcode (0x01,"LD BC,$nn",10,0,"",true),
            new DOpcode (0x02,"LD (BC),A",7,0,"",true),
            new DOpcode (0x03,"INC BC",6,0,"",true),
            new DOpcode (0x04,"INC B",4,0,"",true),
            new DOpcode (0x05,"DEC B",4,0,"",true),
            new DOpcode (0x06,"LD B,$b",7,0,"",true),
            new DOpcode (0x07,"RLCA",4,0,"",true),
            new DOpcode (0x08,"EX AF,AF'",4,0,"",true),
            new DOpcode (0x09,"ADD HL,BC",11,0,"",true),
            new DOpcode (0x0A,"LD A,(BC)",7,0,"",true),
            new DOpcode (0x0B,"DEC BC",6,0,"",true),
            new DOpcode (0x0C,"INC C",4,0,"",true),
            new DOpcode (0x0D,"DEC C",4,0,"",true),
            new DOpcode (0x0E,"LD C,$b",7,0,"",true),
            new DOpcode (0x0F,"RRCA",4,0,"",true),
            new DOpcode (0x10,"DJNZ $d",8,13,"Branch Conditional",true),
            new DOpcode (0x11,"LD DE,$nn",10,0,"",true),
            new DOpcode (0x12,"LD (DE),A",7,0,"",true),
            new DOpcode (0x13,"INC DE",6,0,"",true),
            new DOpcode (0x14,"INC D",4,0,"",true),
            new DOpcode (0x15,"DEC D",4,0,"",true),
            new DOpcode (0x16,"LD D,$b",7,0,"",true),
            new DOpcode (0x17,"RLA",4,0,"",true),
            new DOpcode (0x18,"JR $d",12,0,"Branch Terminal",true),
            new DOpcode (0x19,"ADD HL,DE",11,0,"",true),
            new DOpcode (0x1A,"LD A,(DE)",7,0,"",true),
            new DOpcode (0x1B,"DEC DE",6,0,"",true),
            new DOpcode (0x1C,"INC E",4,0,"",true),
            new DOpcode (0x1D,"DEC E",4,0,"",true),
            new DOpcode (0x1E,"LD E,$b",7,0,"",true),
            new DOpcode (0x1F,"RRA",4,0,"",true),
            new DOpcode (0x20,"JR NZ,$d",7,12,"Branch Conditional",true),
            new DOpcode (0x21,"LD HL,$nn",10,0,"",true),
            new DOpcode (0x22,"LD ($nn),HL",16,0,"Indirect",true),
            new DOpcode (0x23,"INC HL",6,0,"",true),
            new DOpcode (0x24,"INC H",4,0,"",true),
            new DOpcode (0x25,"DEC H",4,0,"",true),
            new DOpcode (0x26,"LD H,$b",7,0,"",true),
            new DOpcode (0x27,"DAA",4,0,"",true),
            new DOpcode (0x28,"JR Z,$d",7,12,"Branch Conditional",true),
            new DOpcode (0x29,"ADD HL,HL",11,0,"",true),
            new DOpcode (0x2A,"LD HL,($nn)",16,0,"Indirect",true),
            new DOpcode (0x2B,"DEC HL",6,0,"",true),
            new DOpcode (0x2C,"INC L",4,0,"",true),
            new DOpcode (0x2D,"DEC L",4,0,"",true),
            new DOpcode (0x2E,"LD L,$b",7,0,"",true),
            new DOpcode (0x2F,"CPL",4,0,"",true),
            new DOpcode (0x30,"JR NC,$d",7,12,"Branch Conditional",true),
            new DOpcode (0x31,"LD SP,$nn",10,0,"",true),
            new DOpcode (0x32,"LD ($nn),A",13,0,"Indirect",true),
            new DOpcode (0x33,"INC SP",6,0,"",true),
            new DOpcode (0x34,"INC (HL)",11,0,"",true),
            new DOpcode (0x35,"DEC (HL)",11,0,"",true),
            new DOpcode (0x36,"LD (HL),$b",10,0,"",true),
            new DOpcode (0x37,"SCF",4,0,"",true),
            new DOpcode (0x38,"JR C,$d",7,12,"Branch Conditional",true),
            new DOpcode (0x39,"ADD HL,SP",11,0,"",true),
            new DOpcode (0x3A,"LD A,($nn)",13,0,"Indirect",true),
            new DOpcode (0x3B,"DEC SP",6,0,"",true),
            new DOpcode (0x3C,"INC A",4,0,"",true),
            new DOpcode (0x3D,"DEC A",4,0,"",true),
            new DOpcode (0x3E,"LD A,$b",7,0,"",true),
            new DOpcode (0x3F,"CCF",4,0,"",true),
            new DOpcode (0x40,"LD B,B",4,0,"",true),
            new DOpcode (0x41,"LD B,C",4,0,"",true),
            new DOpcode (0x42,"LD B,D",4,0,"",true),
            new DOpcode (0x43,"LD B,E",4,0,"",true),
            new DOpcode (0x44,"LD B,H",4,0,"",true),
            new DOpcode (0x45,"LD B,L",4,0,"",true),
            new DOpcode (0x46,"LD B,(HL)",7,0,"",true),
            new DOpcode (0x47,"LD B,A",4,0,"",true),
            new DOpcode (0x48,"LD C,B",4,0,"",true),
            new DOpcode (0x49,"LD C,C",4,0,"",true),
            new DOpcode (0x4A,"LD C,D",4,0,"",true),
            new DOpcode (0x4B,"LD C,E",4,0,"",true),
            new DOpcode (0x4C,"LD C,H",4,0,"",true),
            new DOpcode (0x4D,"LD C,L",4,0,"",true),
            new DOpcode (0x4E,"LD C,(HL)",7,0,"",true),
            new DOpcode (0x4F,"LD C,A",4,0,"",true),
            new DOpcode (0x50,"LD D,B",4,0,"",true),
            new DOpcode (0x51,"LD D,C",4,0,"",true),
            new DOpcode (0x52,"LD D,D",4,0,"",true),
            new DOpcode (0x53,"LD D,E",4,0,"",true),
            new DOpcode (0x54,"LD D,H",4,0,"",true),
            new DOpcode (0x55,"LD D,L",4,0,"",true),
            new DOpcode (0x56,"LD D,(HL)",7,0,"",true),
            new DOpcode (0x57,"LD D,A",4,0,"",true),
            new DOpcode (0x58,"LD E,B",4,0,"",true),
            new DOpcode (0x59,"LD E,C",4,0,"",true),
            new DOpcode (0x5A,"LD E,D",4,0,"",true),
            new DOpcode (0x5B,"LD E,E",4,0,"",true),
            new DOpcode (0x5C,"LD E,H",4,0,"",true),
            new DOpcode (0x5D,"LD E,L",4,0,"",true),
            new DOpcode (0x5E,"LD E,(HL)",7,0,"",true),
            new DOpcode (0x5F,"LD E,A",4,0,"",true),
            new DOpcode (0x60,"LD H,B",4,0,"",true),
            new DOpcode (0x61,"LD H,C",4,0,"",true),
            new DOpcode (0x62,"LD H,D",4,0,"",true),
            new DOpcode (0x63,"LD H,E",4,0,"",true),
            new DOpcode (0x64,"LD H,H",4,0,"",true),
            new DOpcode (0x65,"LD H,L",4,0,"",true),
            new DOpcode (0x66,"LD H,(HL)",7,0,"",true),
            new DOpcode (0x67,"LD H,A",4,0,"",true),
            new DOpcode (0x68,"LD L,B",4,0,"",true),
            new DOpcode (0x69,"LD L,C",4,0,"",true),
            new DOpcode (0x6A,"LD L,D",4,0,"",true),
            new DOpcode (0x6B,"LD L,E",4,0,"",true),
            new DOpcode (0x6C,"LD L,H",4,0,"",true),
            new DOpcode (0x6D,"LD L,L",4,0,"",true),
            new DOpcode (0x6E,"LD L,(HL)",7,0,"",true),
            new DOpcode (0x6F,"LD L,A",4,0,"",true),
            new DOpcode (0x70,"LD (HL),B",7,0,"",true),
            new DOpcode (0x71,"LD (HL),C",7,0,"",true),
            new DOpcode (0x72,"LD (HL),D",7,0,"",true),
            new DOpcode (0x73,"LD (HL),E",7,0,"",true),
            new DOpcode (0x74,"LD (HL),H",7,0,"",true),
            new DOpcode (0x75,"LD (HL),L",7,0,"",true),
            new DOpcode (0x76,"HALT",4,0,"",true),
            new DOpcode (0x77,"LD (HL),A",7,0,"",true),
            new DOpcode (0x78,"LD A,B",4,0,"",true),
            new DOpcode (0x79,"LD A,C",4,0,"",true),
            new DOpcode (0x7A,"LD A,D",4,0,"",true),
            new DOpcode (0x7B,"LD A,E",4,0,"",true),
            new DOpcode (0x7C,"LD A,H",4,0,"",true),
            new DOpcode (0x7D,"LD A,L",4,0,"",true),
            new DOpcode (0x7E,"LD A,(HL)",7,0,"",true),
            new DOpcode (0x7F,"LD A,A",4,0,"",true),
            new DOpcode (0x80,"ADD A,B",4,0,"",true),
            new DOpcode (0x81,"ADD A,C",4,0,"",true),
            new DOpcode (0x82,"ADD A,D",4,0,"",true),
            new DOpcode (0x83,"ADD A,E",4,0,"",true),
            new DOpcode (0x84,"ADD A,H",4,0,"",true),
            new DOpcode (0x85,"ADD A,L",4,0,"",true),
            new DOpcode (0x86,"ADD A,(HL)",7,0,"",true),
            new DOpcode (0x87,"ADD A,A",4,0,"",true),
            new DOpcode (0x88,"ADC A,B",4,0,"",true),
            new DOpcode (0x89,"ADC A,C",4,0,"",true),
            new DOpcode (0x8A,"ADC A,D",4,0,"",true),
            new DOpcode (0x8B,"ADC A,E",4,0,"",true),
            new DOpcode (0x8C,"ADC A,H",4,0,"",true),
            new DOpcode (0x8D,"ADC A,L",4,0,"",true),
            new DOpcode (0x8E,"ADC A,(HL)",7,0,"",true),
            new DOpcode (0x8F,"ADC A,A",4,0,"",true),
            new DOpcode (0x90,"SUB B",4,0,"",true),
            new DOpcode (0x91,"SUB C",4,0,"",true),
            new DOpcode (0x92,"SUB D",4,0,"",true),
            new DOpcode (0x93,"SUB E",4,0,"",true),
            new DOpcode (0x94,"SUB H",4,0,"",true),
            new DOpcode (0x95,"SUB L",4,0,"",true),
            new DOpcode (0x96,"SUB (HL)",7,0,"",true),
            new DOpcode (0x97,"SUB A",4,0,"",true),
            new DOpcode (0x98,"SBC A,B",4,0,"",true),
            new DOpcode (0x99,"SBC A,C",4,0,"",true),
            new DOpcode (0x9A,"SBC A,D",4,0,"",true),
            new DOpcode (0x9B,"SBC A,E",4,0,"",true),
            new DOpcode (0x9C,"SBC A,H",4,0,"",true),
            new DOpcode (0x9D,"SBC A,L",4,0,"",true),
            new DOpcode (0x9E,"SBC A,(HL)",7,0,"",true),
            new DOpcode (0x9F,"SBC A,A",4,0,"",true),
            new DOpcode (0xA0,"AND B",4,0,"",true),
            new DOpcode (0xA1,"AND C",4,0,"",true),
            new DOpcode (0xA2,"AND D",4,0,"",true),
            new DOpcode (0xA3,"AND E",4,0,"",true),
            new DOpcode (0xA4,"AND H",4,0,"",true),
            new DOpcode (0xA5,"AND L",4,0,"",true),
            new DOpcode (0xA6,"AND (HL)",7,0,"",true),
            new DOpcode (0xA7,"AND A",4,0,"",true),
            new DOpcode (0xA8,"XOR B",4,0,"",true),
            new DOpcode (0xA9,"XOR C",4,0,"",true),
            new DOpcode (0xAA,"XOR D",4,0,"",true),
            new DOpcode (0xAB,"XOR E",4,0,"",true),
            new DOpcode (0xAC,"XOR H",4,0,"",true),
            new DOpcode (0xAD,"XOR L",4,0,"",true),
            new DOpcode (0xAE,"XOR (HL)",7,0,"",true),
            new DOpcode (0xAF,"XOR A",4,0,"",true),
            new DOpcode (0xB0,"OR B",4,0,"",true),
            new DOpcode (0xB1,"OR C",4,0,"",true),
            new DOpcode (0xB2,"OR D",4,0,"",true),
            new DOpcode (0xB3,"OR E",4,0,"",true),
            new DOpcode (0xB4,"OR H",4,0,"",true),
            new DOpcode (0xB5,"OR L",4,0,"",true),
            new DOpcode (0xB6,"OR (HL)",7,0,"",true),
            new DOpcode (0xB7,"OR A",4,0,"",true),
            new DOpcode (0xB8,"CP B",4,0,"",true),
            new DOpcode (0xB9,"CP C",4,0,"",true),
            new DOpcode (0xBA,"CP D",4,0,"",true),
            new DOpcode (0xBB,"CP E",4,0,"",true),
            new DOpcode (0xBC,"CP H",4,0,"",true),
            new DOpcode (0xBD,"CP L",4,0,"",true),
            new DOpcode (0xBE,"CP (HL)",7,0,"",true),
            new DOpcode (0xBF,"CP A",4,0,"",true),
            new DOpcode (0xC0,"RET NZ",5,11,"Return Conditional",true),
            new DOpcode (0xC1,"POP BC",10,0,"",true),
            new DOpcode (0xC2,"JP NZ,$aa",10,0,"Branch Conditional",true),
            new DOpcode (0xC3,"JP $aa",10,0,"Branch Terminal",true),
            new DOpcode (0xC4,"CALL NZ,$aa",10,17,"Branch Conditional Call",true),
            new DOpcode (0xC5,"PUSH BC",11,0,"",true),
            new DOpcode (0xC6,"ADD A,$b",7,0,"",true),
            new DOpcode (0xC7,"RST 00H",11,0,"Restart",true),
            new DOpcode (0xC8,"RET Z",5,11,"Return Conditional",true),
            new DOpcode (0xC9,"RET",10,0,"Return Terminal",true),
            new DOpcode (0xCA,"JP Z,$aa",10,0,"Branch Conditional",true),
            new DOpcode (0xCB,"AfterCB",4,0,"",true),
            new DOpcode (0xCC,"CALL Z,$aa",10,17,"Branch Conditional Call",true),
            new DOpcode (0xCD,"CALL $aa",17,0,"Branch Call",true),
            new DOpcode (0xCE,"ADC A,$b",7,0,"",true),
            new DOpcode (0xCF,"RST 08H",11,0,"Restart",true),
            new DOpcode (0xD0,"RET NC",5,11,"Return Conditional",true),
            new DOpcode (0xD1,"POP DE",10,0,"",true),
            new DOpcode (0xD2,"JP NC,$aa",10,0,"Branch Conditional",true),
            new DOpcode (0xD3,"OUT ($b),A",11,0," Port Call",true),
            new DOpcode (0xD4,"CALL NC,$aa",10,17,"Branch Conditional Call",true),
            new DOpcode (0xD5,"PUSH DE",11,0,"",true),
            new DOpcode (0xD6,"SUB $b",7,0,"",true),
            new DOpcode (0xD7,"RST 10H",11,0,"Restart",true),
            new DOpcode (0xD8,"RET C",5,11,"Return Conditional",true),
            new DOpcode (0xD9,"EXX",4,0,"",true),
            new DOpcode (0xDA,"JP C,$aa",10,0,"Branch Conditional",true),
            new DOpcode (0xDB,"IN A,($b)",11,0," Port",true),
            new DOpcode (0xDC,"CALL C,$aa",10,17,"Branch Conditional Call",true),
            new DOpcode (0xDD,"AfterDD",0,0,"",true),
            new DOpcode (0xDE,"SBC A,$b",7,0,"",true),
            new DOpcode (0xDF,"RST 18H",11,0,"Restart",true),
            new DOpcode (0xE0,"RET PO",5,11,"Return Conditional",true),
            new DOpcode (0xE1,"POP HL",10,0,"",true),
            new DOpcode (0xE2,"JP PO,$aa",10,0,"Branch Conditional",true),
            new DOpcode (0xE3,"EX (SP),HL",19,0,"",true),
            new DOpcode (0xE4,"CALL PO,$aa",10,17,"Branch Conditional Call",true),
            new DOpcode (0xE5,"PUSH HL",11,0,"",true),
            new DOpcode (0xE6,"AND $b",7,0,"",true),
            new DOpcode (0xE7,"RST 20H",11,0,"Restart",true),
            new DOpcode (0xE8,"RET PE",5,11,"Return Conditional",true),
            new DOpcode (0xE9,"JP (HL)",4,0,"Branch Terminal",true),
            new DOpcode (0xEA,"JP PE,$aa",10,0,"Branch Conditional",true),
            new DOpcode (0xEB,"EX DE,HL",4,0,"",true),
            new DOpcode (0xEC,"CALL PE,$aa",10,17,"Branch Conditional Call",true),
            new DOpcode (0xED,"AfterED",0,0,"",true),
            new DOpcode (0xEE,"XOR $b",7,0,"",true),
            new DOpcode (0xEF,"RST 28H",11,0,"Restart",true),
            new DOpcode (0xF0,"RET P",5,11,"Return Conditional",true),
            new DOpcode (0xF1,"POP AF",10,0,"",true),
            new DOpcode (0xF2,"JP P,$aa",10,0,"Branch Conditional",true),
            new DOpcode (0xF3,"DI",4,0,"",true),
            new DOpcode (0xF4,"CALL P,$aa",10,17,"Branch Conditional Call",true),
            new DOpcode (0xF5,"PUSH AF",11,0,"",true),
            new DOpcode (0xF6,"OR $b",7,0,"",true),
            new DOpcode (0xF7,"RST 30H",11,0,"Restart",true),
            new DOpcode (0xF8,"RET M",5,11,"Return Conditional",true),
            new DOpcode (0xF9,"LD SP,HL",6,0,"",true),
            new DOpcode (0xFA,"JP M,$aa",10,0,"Branch Conditional",true),
            new DOpcode (0xFB,"EI",4,0,"",true),
            new DOpcode (0xFC,"CALL M,$aa",10,17,"Branch Conditional Call",true),
            new DOpcode (0xFD,"AfterFD",4,0,"",true),
            new DOpcode (0xFE,"CP $b",7,0,"",true),
            new DOpcode (0xFF,"RST 38H",11,0,"Restart",true)
        };
    }
}

